# Uncomment the next line to define a global platform for your project
post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.5'
  end
 end
end
platform :ios, '14.5'
inhibit_all_warnings!

target 'ChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MessageKit'
  pod 'SDWebImage'
  
  #UI
  pod 'IQKeyboardManager'
  pod 'JGProgressHUD'
  
  #DB
  pod 'FirebaseAuth' , '10.8.0'
  pod 'FirebaseDatabase' ,'10.8.0'
  pod 'FirebaseStorage' , '10.8.0'
  pod 'RealmSwift', '10.38.3'

  
  #Facebook
  pod 'FBSDKLoginKit', '12.0.2'
  
  #Google
  pod 'GoogleSignIn'

end
